# Principal informations
name = "dashboard"
main = "src/index.js"
compatibility_date = "2026-05-22"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

# Environement variables
[vars]
MODE = "production" # -> "production" if enabled, or any other name if disabled
SITE = "enabled" # -> "enabled" if enabled, or any other name if disabled
JWT_SECRET = "generate-a-secure-random-key"
JWT = "generate-a-secure-random-key"
GATEWAY_ID = "dashboard-gateway"

# Production environment
[env.production]
vars = { JWT_SECRET = "generate-a-secure-random-key", JWT = "generate-a-secure-random-key" }

# Static site
[assets]
directory = "./src/frontend"
binding = "ASSETS"

# Worker AI
[ai]
name = "AI"
binding = "AI"

# Gateway AI for storage
[gateway_ai]
name = "GATEWAY_AI"
binding = "GATEWAY_AI"

# Worker executed before assets
run_worker_first = [
  "/sitemap.xml",
  "/robots.txt",
  "/assets",
  "/api/ed",
  "/api/config",
  "/api/auth",
  "/api/pomodoro",
  "/pages/auth",
  "/pages/auth/",
  "/pages/error-token",
  "/pages/error-token/",
  "/pages/home",
  "/pages/home/",
  "/pages/workspace",
  "/pages/workspace/",
  "/pages/ai",
  "/pages/ai/",
  "/pages/files",
  "/pages/files/",
  "/pages/tools",
  "/pages/tools/",
  "/pages/settings",
  "/pages/settings/"
]

# Workflows
#[[workflows]]
#name = "check_grades"
#binding = "CHECK_GRADES"
#class_name = "CheckGradesWorkflow"

# Cron triggers
#[triggers]
#crons = ["0 */4 * * *"]  # Vérifier les notes toutes les 4 heures

# Observability
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
