# Principal informations
name = "workspace"
main = "src/index.js"
compatibility_date = "2026-05-22"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

# Environnement variables
[vars]
MODE = "production" # -> "production" if enabled, or any other name if disabled
SITE = "enabled" # -> "enabled" if enabled, or any other name if disabled

# Static site
[assets]
directory = "./src/frontend"
binding = "ASSETS"

# Secret store
[[secrets_store_secrets]]
binding = "MY_SECRET"
store_id = "66ec2510845d44729eeef43b8f0a7f65"
secret_name = "SECRET_KEY"

# Worker AI
[ai]
binding = "AI"

# Worker executed before assets
run_worker_first = [
  "/api/ed"
]

# Workflows
[workflows]
name = "check_grades"

# Observability
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
